In [2]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
import pandas as pd
import numpy as np

In [4]:
iris = datasets.load_iris()
X =pd.DataFrame(iris.data)
X.columns =['Sepal_Length','Sepal_width','Petal_Length','Petal_Width']
print(X)

     Sepal_Length  Sepal_width  Petal_Length  Petal_Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [6]:
y =pd.DataFrame(iris.target)
y.columns=['Targets']
print(y)

     Targets
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]


In [10]:
x_train,x_test,y_train,y_test =train_test_split(iris.data,iris.target,test_size=0.1)
print("Dataset is split into training and testing....")
print("Size of training data and its label",x_train.shape,y_train.shape)
print("Size of testing data and its label",x_test.shape,y_test.shape)

Dataset is split into training and testing....
Size of training data and its label (135, 4) (135,)
Size of testing data and its label (15, 4) (15,)


In [11]:
for i in range(len(iris.target_names)):
    print("Label",i,"-",str(iris.target_names[i]))

Label 0 - setosa
Label 1 - versicolor
Label 2 - virginica


In [15]:
classifer =KNeighborsClassifier(n_neighbors=3)

In [16]:
classifer.fit(x_train,y_train)
y_pred=classifer.predict(x_test)

In [17]:
print("Results of Classification using K-nn with K=3")
for r in range(0,len(x_test)):
    print("Sample:", str(x_test[r]), "Actual-label:",str(y_test[r]),"predict-label:",str(y_pred[r]))
    print("Classification accuracy:",classifer.score(x_test,y_test))

Results of Classification using K-nn with K=3
Sample: [5.5 2.5 4.  1.3] Actual-label: 1 predict-label: 1
Classification accuracy: 1.0
Sample: [5.9 3.  5.1 1.8] Actual-label: 2 predict-label: 2
Classification accuracy: 1.0
Sample: [7.4 2.8 6.1 1.9] Actual-label: 2 predict-label: 2
Classification accuracy: 1.0
Sample: [5.1 3.8 1.5 0.3] Actual-label: 0 predict-label: 0
Classification accuracy: 1.0
Sample: [7.7 3.  6.1 2.3] Actual-label: 2 predict-label: 2
Classification accuracy: 1.0
Sample: [5.6 2.7 4.2 1.3] Actual-label: 1 predict-label: 1
Classification accuracy: 1.0
Sample: [5.5 2.4 3.7 1. ] Actual-label: 1 predict-label: 1
Classification accuracy: 1.0
Sample: [6.1 2.8 4.  1.3] Actual-label: 1 predict-label: 1
Classification accuracy: 1.0
Sample: [6.3 3.3 6.  2.5] Actual-label: 2 predict-label: 2
Classification accuracy: 1.0
Sample: [6.3 3.4 5.6 2.4] Actual-label: 2 predict-label: 2
Classification accuracy: 1.0
Sample: [5.8 4.  1.2 0.2] Actual-label: 0 predict-label: 0
Classification 

In [19]:
from sklearn.metrics import classification_report,confusion_matrix
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('Accuracy ketrics')
print(classification_report(y_test,y_pred))

Confusion Matrix
[[4 0 0]
 [0 5 0]
 [0 0 6]]
Accuracy ketrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

