In [6]:
from sklearn.model_selection import train_test_split
from sklearn import datasets
import pandas as pd
import numpy as np

In [7]:
iris =datasets.load_iris()
iris =datasets.load_iris()
X =pd.DataFrame(iris.data)
X.columns=['Sepal_length','sepal_width','Petal_length','Petal_Width']
print(X)

     Sepal_length  sepal_width  Petal_length  Petal_Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [8]:
y=pd.DataFrame(iris.target)
y.columns=['Targets']
print(y)

     Targets
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]


In [9]:
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.1)

In [10]:
from sklearn.svm import SVC
model=SVC()
SVC=model.fit(x_train,y_train)

In [11]:
y_pred=SVC.predict(x_test)

In [12]:
from sklearn.metrics import classification_report,confusion_matrix
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('Accuracy  Ketrics')
print(classification_report(y_test,y_pred))

Confusion Matrix
[[3 0 0]
 [0 6 0]
 [0 1 5]]
Accuracy  Ketrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       0.86      1.00      0.92         6
           2       1.00      0.83      0.91         6

    accuracy                           0.93        15
   macro avg       0.95      0.94      0.94        15
weighted avg       0.94      0.93      0.93        15

